[package]
name = "gaming"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
color-rs = "0.7.1"
dyn-clonable = "0.9.0"
plotters = "0.3.2"
rand = "0.8.5"
thiserror = "1.0.31"
